# THIS FILE IS AUTOMATICALLY GENERATED. IT IS POINTLESS TO MODIFY IT

from setuptools import setup

description = 'Philips hue toolkit'

setup(
    name='hue',
    version='1.0.0',
    packages=['hue'],
    # url='https://github.com/ddorn/man',
    license='MIT',
    author='Diego Dorn',
    author_email='diego.dorn@free.fr',
    description=description,
    long_description=description,
    # install_requires=[],
    # include_package_data=True,
    scripts=['hue/hue.py'],
    install_requires=['ansimarkup', 'click', ],
    keywords='hue philips lights automation sexy'
)

